/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 30 21:39:28 GMT 2024
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.WeightHelper;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WeightHelper_ESTest extends WeightHelper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = WeightHelper.getCategory(100.0, 30.0);
      assertEquals("Obese", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = WeightHelper.getCategory(100.0, 18.5);
      assertEquals("Normal weight", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      // Undeclared exception!
      try { 
        WeightHelper.getCategory(30.0, 300.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Write values for height and weight below 250.0 kg or 300.0 cm.
         //
         verifyException("org.example.WeightHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        WeightHelper.calculateBMI(250.0, 3784.172643);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Write values for height and weight below 250.0 kg or 300.0 cm.
         //
         verifyException("org.example.WeightHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        WeightHelper.getCategory(1827.097019, 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Write values for height and weight above 0 kg or 0 cm.
         //
         verifyException("org.example.WeightHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        WeightHelper.calculateBMI(0.0, 1.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Write values for height and weight above 0 kg or 0 cm.
         //
         verifyException("org.example.WeightHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        WeightHelper.calculateBMI(2770.6611677645387, (-1.0));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Write values for height and weight above 0 kg or 0 cm.
         //
         verifyException("org.example.WeightHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = WeightHelper.getCategory(100.0, 25.0);
      assertEquals("Overweight", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = WeightHelper.getCategory(21.237377607566422, 1.0);
      assertEquals("Normal weight", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = WeightHelper.getCategory(100.0, 1.0);
      assertEquals("Underweight", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = WeightHelper.getCategory(18.243, 18.243);
      assertEquals("Obese", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        WeightHelper.calculateBMI(1.5225577774255705, 886.757040671143);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Write values for height and weight below 250.0 kg or 300.0 cm.
         //
         verifyException("org.example.WeightHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        WeightHelper.calculateBMI(548.1554568875735, 18.243);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Write values for height and weight below 250.0 kg or 300.0 cm.
         //
         verifyException("org.example.WeightHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      double double0 = WeightHelper.calculateBMI(1.0, 1.0);
      assertEquals(10000.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      // Undeclared exception!
      try { 
        WeightHelper.calculateBMI((-55.0), (-55.0));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Write values for height and weight above 0 kg or 0 cm.
         //
         verifyException("org.example.WeightHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
  }
}
